# Generated by Django 4.1 on 2022-11-16 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                ("web", models.CharField(max_length=64, null=True)),
                (
                    "bio",
                    models.TextField(
                        help_text="Escribir biografia", max_length=400, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "sumario",
                    models.TextField(
                        help_text="Colocar el resumen de la peli",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cineapp.director",
                    ),
                ),
            ],
        ),
    ]
